% exercise 5.1.6

% Fit classification tree
T = classregtree(X, classNames(y+1), ...
    'method', 'classification', ...
    'splitcriterion', 'gdi', ...
    'categorical', [], ...
    'names', attributeNames, ...
    'prune', 'off', ...
    'minparent', 100);

% View the tree
view(T)
