% exercise 5.1.2

% Fit classification tree
T = classregtree(X, classNames(y+1), ...
    'method', 'classification', ...
    'splitcriterion', 'gdi', ...
    'categorical', 1:M, ...
    'names', attributeNames, ...
    'prune', 'off', ...
    'minparent', 1);

% View the tree
view(T)
